=== Manu-1899/assegnazione-computer/alunni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="Sezione">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Alunno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nome" type="xs:string"/>
                            <xs:element name="Cognome" type="xs:string"/>
                            <xs:element name="Dispositivo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="os" type="xs:string"/>
                                        <xs:element name="app" type="xs:string"
                                                    minOccurs="0"
                                                    maxOccurs="unbounded"/>
                                        <xs:element name="Data_assegnazione"
                                                    type="xs:string"
                                                    minOccurs="0"/>
                                        <xs:element name="Data_utilizzo" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="tipo" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Personale"/>
                                                <xs:enumeration value="Scolastico"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="codice" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== Manu-1899/assegnazione-computer/alunni.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="stile.css"?>
<Sezione id="5AIA"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="alunni.xsd">
    <Alunno>
        <Nome>Francesco</Nome>
        <Cognome>Savino</Cognome>
        <Dispositivo tipo="Personale">
            <os>Linux</os>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Giuseppe</Nome>
        <Cognome>Caldarola</Cognome>
        <Dispositivo tipo="Scolastico" codice="6087">
            <os>IOS</os>
            <Data_assegnazione>08/10/2026</Data_assegnazione>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Emanuele</Nome>
        <Cognome>Lovascio</Cognome>
        <Dispositivo tipo="Scolastico" codice="6102">
            <os>IOS</os>
            <app>Vscode</app>
            <Data_assegnazione>08/10/2026</Data_assegnazione>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Gaetano</Nome>
        <Cognome>Napoli</Cognome>
        <Dispositivo tipo="Scolastico" codice="6103">
            <os>IOS</os>
            <app>Vscode</app>
            <Data_assegnazione>08/10/2026</Data_assegnazione>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Claudio</Nome>
        <Cognome>DeChiara</Cognome>
        <Dispositivo tipo="Scolastico" codice="6091">
            <os>IOS</os>
            <app>Vscode</app>
            <Data_assegnazione>08/10/2026</Data_assegnazione>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Gianvito</Nome>
        <Cognome>Paparella</Cognome>
        <Dispositivo tipo="Scolastico" codice="6104">
            <os>IOS</os>
            <app>Vscode</app>
            <Data_assegnazione>08/10/2026</Data_assegnazione>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Lorenzo</Nome>
        <Cognome>Lavacca</Cognome>
        <Dispositivo tipo="Personale">
            <os>Windows</os>
            <app>Linux SubSystem</app>
            <app>VScode</app>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Nicolas</Nome>
        <Cognome>Rizzi</Cognome>
        <Dispositivo tipo="Personale">
            <os>Windows</os>
            <app>VScode</app>
            <Data_utilizzo>08/10/2026</Data_utilizzo>
        </Dispositivo>
    </Alunno>
    <Alunno>
        <Nome>Luca</Nome>
        <Cognome>Caldarola</Cognome>
        <Dispositivo tipo="Scolastico" codice="6074">
            <os>IOS</os>
            <app>Na</app>
            <Data_assegnazione>Na</Data_assegnazione>
            <Data_utilizzo>Na</Data_utilizzo>
        </Dispositivo>
    </Alunno>
</Sezione>
